export interface Player {
  name: string
  country: string
  currentTeam: string
  league: string
  position: string
}

// Función para normalizar texto (remover acentos y convertir a minúsculas)
function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // Remover acentos
    .replace(/[^a-z0-9\s]/g, "") // Remover caracteres especiales excepto espacios
    .trim()
}

// Jugadores destacados para mostrar en la página principal
export const FEATURED_PLAYERS: Player[] = [
  { name: "Lionel Messi", country: "Argentina", currentTeam: "Inter Miami", league: "MLS", position: "Delantero" },
  {
    name: "Cristiano Ronaldo",
    country: "Portugal",
    currentTeam: "Al-Nassr",
    league: "Saudi Pro League",
    position: "Delantero",
  },
  { name: "Kylian Mbappé", country: "Francia", currentTeam: "Real Madrid", league: "La Liga", position: "Delantero" },
  {
    name: "Erling Haaland",
    country: "Noruega",
    currentTeam: "Manchester City",
    league: "Premier League",
    position: "Delantero",
  },
  { name: "Vinícius Jr", country: "Brasil", currentTeam: "Real Madrid", league: "La Liga", position: "Extremo" },
  {
    name: "Jude Bellingham",
    country: "Inglaterra",
    currentTeam: "Real Madrid",
    league: "La Liga",
    position: "Centrocampista",
  },
  {
    name: "Ángel Di María",
    country: "Argentina",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Extremo",
  },
  {
    name: "Lautaro Martínez",
    country: "Argentina",
    currentTeam: "Inter Milan",
    league: "Serie A",
    position: "Delantero",
  },
  {
    name: "Julián Álvarez",
    country: "Argentina",
    currentTeam: "Atlético Madrid",
    league: "La Liga",
    position: "Delantero",
  },
  {
    name: "Enzo Fernández",
    country: "Argentina",
    currentTeam: "Chelsea",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Alexis Mac Allister",
    country: "Argentina",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Emiliano Martínez",
    country: "Argentina",
    currentTeam: "Aston Villa",
    league: "Premier League",
    position: "Portero",
  },
]

// Base de datos completa de jugadores
export const ALL_PLAYERS: Player[] = [
  // Liga Profesional Argentina - Top 30
  {
    name: "Miguel Borja",
    country: "Colombia",
    currentTeam: "River Plate",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Franco Armani",
    country: "Argentina",
    currentTeam: "River Plate",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Edinson Cavani",
    country: "Uruguay",
    currentTeam: "Boca Juniors",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Sergio Romero",
    country: "Argentina",
    currentTeam: "Boca Juniors",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Juan Fernando Quintero",
    country: "Colombia",
    currentTeam: "Racing Club",
    league: "Liga Profesional",
    position: "Centrocampista",
  },
  {
    name: "Adrián Martínez",
    country: "Argentina",
    currentTeam: "Racing Club",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Gabriel Ávalos",
    country: "Paraguay",
    currentTeam: "Independiente",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Rodrigo Rey",
    country: "Argentina",
    currentTeam: "Independiente",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Adam Bareiro",
    country: "Paraguay",
    currentTeam: "San Lorenzo",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Gastón Gómez",
    country: "Argentina",
    currentTeam: "San Lorenzo",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Ramón Ábila",
    country: "Argentina",
    currentTeam: "Huracán",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Hernán Galíndez",
    country: "Ecuador",
    currentTeam: "Huracán",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Braian Romero",
    country: "Argentina",
    currentTeam: "Vélez Sarsfield",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Tomás Marchiori",
    country: "Argentina",
    currentTeam: "Vélez Sarsfield",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Guido Carrillo",
    country: "Argentina",
    currentTeam: "Estudiantes",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Matías Mansilla",
    country: "Argentina",
    currentTeam: "Estudiantes",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Benjamín Rollheiser",
    country: "Argentina",
    currentTeam: "Gimnasia La Plata",
    league: "Liga Profesional",
    position: "Extremo",
  },
  {
    name: "Marcos Ledesma",
    country: "Argentina",
    currentTeam: "Gimnasia La Plata",
    league: "Liga Profesional",
    position: "Portero",
  },
  { name: "Walter Bou", country: "Argentina", currentTeam: "Lanús", league: "Liga Profesional", position: "Delantero" },
  { name: "Alan Aguerre", country: "Uruguay", currentTeam: "Lanús", league: "Liga Profesional", position: "Portero" },
  {
    name: "Juan Bisanz",
    country: "Argentina",
    currentTeam: "Banfield",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Facundo Soto",
    country: "Argentina",
    currentTeam: "Banfield",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Nicolás Fernández",
    country: "Argentina",
    currentTeam: "Defensa y Justicia",
    league: "Liga Profesional",
    position: "Centrocampista",
  },
  {
    name: "Enrique Bologna",
    country: "Argentina",
    currentTeam: "Defensa y Justicia",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Federico Girotti",
    country: "Argentina",
    currentTeam: "Talleres",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Guido Herrera",
    country: "Argentina",
    currentTeam: "Talleres",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Javier Correa",
    country: "Argentina",
    currentTeam: "Estudiantes",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Facundo Altamirano",
    country: "Argentina",
    currentTeam: "Estudiantes",
    league: "Liga Profesional",
    position: "Portero",
  },
  {
    name: "Mateo Retegui",
    country: "Argentina",
    currentTeam: "Tigre",
    league: "Liga Profesional",
    position: "Delantero",
  },
  {
    name: "Felipe Zenobio",
    country: "Argentina",
    currentTeam: "Tigre",
    league: "Liga Profesional",
    position: "Portero",
  },

  // Brasileirão - Top 30
  { name: "Pedro", country: "Brasil", currentTeam: "Flamengo", league: "Brasileirão", position: "Delantero" },
  { name: "Gabigol", country: "Brasil", currentTeam: "Flamengo", league: "Brasileirão", position: "Delantero" },
  {
    name: "Giorgian de Arrascaeta",
    country: "Uruguay",
    currentTeam: "Flamengo",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  {
    name: "Raphael Veiga",
    country: "Brasil",
    currentTeam: "Palmeiras",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  { name: "Endrick", country: "Brasil", currentTeam: "Real Madrid", league: "La Liga", position: "Delantero" },
  { name: "Rony", country: "Brasil", currentTeam: "Palmeiras", league: "Brasileirão", position: "Delantero" },
  { name: "Yuri Alberto", country: "Brasil", currentTeam: "Corinthians", league: "Brasileirão", position: "Delantero" },
  { name: "Róger Guedes", country: "Brasil", currentTeam: "Corinthians", league: "Brasileirão", position: "Extremo" },
  { name: "Cássio", country: "Brasil", currentTeam: "Corinthians", league: "Brasileirão", position: "Portero" },
  { name: "Luciano", country: "Brasil", currentTeam: "São Paulo", league: "Brasileirão", position: "Delantero" },
  { name: "Calleri", country: "Argentina", currentTeam: "São Paulo", league: "Brasileirão", position: "Delantero" },
  { name: "Rafael", country: "Brasil", currentTeam: "São Paulo", league: "Brasileirão", position: "Portero" },
  { name: "Soteldo", country: "Venezuela", currentTeam: "Santos", league: "Brasileirão", position: "Extremo" },
  { name: "Marcos Leonardo", country: "Brasil", currentTeam: "Santos", league: "Brasileirão", position: "Delantero" },
  { name: "João Paulo", country: "Brasil", currentTeam: "Santos", league: "Brasileirão", position: "Portero" },
  {
    name: "Germán Cano",
    country: "Argentina",
    currentTeam: "Fluminense",
    league: "Brasileirão",
    position: "Delantero",
  },
  {
    name: "Paulo Henrique Ganso",
    country: "Brasil",
    currentTeam: "Fluminense",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  { name: "Fábio", country: "Brasil", currentTeam: "Fluminense", league: "Brasileirão", position: "Portero" },
  { name: "Tiquinho Soares", country: "Brasil", currentTeam: "Botafogo", league: "Brasileirão", position: "Delantero" },
  { name: "Luiz Henrique", country: "Brasil", currentTeam: "Botafogo", league: "Brasileirão", position: "Extremo" },
  { name: "John", country: "Brasil", currentTeam: "Botafogo", league: "Brasileirão", position: "Portero" },
  { name: "Vegetti", country: "Argentina", currentTeam: "Vasco da Gama", league: "Brasileirão", position: "Delantero" },
  {
    name: "Payet",
    country: "Francia",
    currentTeam: "Vasco da Gama",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  { name: "Léo Jardim", country: "Brasil", currentTeam: "Vasco da Gama", league: "Brasileirão", position: "Portero" },
  { name: "Suárez", country: "Uruguay", currentTeam: "Grêmio", league: "Brasileirão", position: "Delantero" },
  {
    name: "Everton Ribeiro",
    country: "Brasil",
    currentTeam: "Grêmio",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  { name: "Marchesín", country: "Argentina", currentTeam: "Grêmio", league: "Brasileirão", position: "Portero" },
  {
    name: "Alan Patrick",
    country: "Brasil",
    currentTeam: "Internacional",
    league: "Brasileirão",
    position: "Centrocampista",
  },
  {
    name: "Enner Valencia",
    country: "Ecuador",
    currentTeam: "Internacional",
    league: "Brasileirão",
    position: "Delantero",
  },
  {
    name: "Sergio Rochet",
    country: "Uruguay",
    currentTeam: "Internacional",
    league: "Brasileirão",
    position: "Portero",
  },

  // La Liga España - Top 30
  { name: "Kylian Mbappé", country: "Francia", currentTeam: "Real Madrid", league: "La Liga", position: "Delantero" },
  { name: "Vinícius Jr", country: "Brasil", currentTeam: "Real Madrid", league: "La Liga", position: "Extremo" },
  {
    name: "Jude Bellingham",
    country: "Inglaterra",
    currentTeam: "Real Madrid",
    league: "La Liga",
    position: "Centrocampista",
  },
  { name: "Rodrygo", country: "Brasil", currentTeam: "Real Madrid", league: "La Liga", position: "Extremo" },
  { name: "Thibaut Courtois", country: "Bélgica", currentTeam: "Real Madrid", league: "La Liga", position: "Portero" },
  {
    name: "Robert Lewandowski",
    country: "Polonia",
    currentTeam: "FC Barcelona",
    league: "La Liga",
    position: "Delantero",
  },
  { name: "Raphinha", country: "Brasil", currentTeam: "FC Barcelona", league: "La Liga", position: "Extremo" },
  { name: "Pedri", country: "España", currentTeam: "FC Barcelona", league: "La Liga", position: "Centrocampista" },
  { name: "Gavi", country: "España", currentTeam: "FC Barcelona", league: "La Liga", position: "Centrocampista" },
  {
    name: "Marc-André ter Stegen",
    country: "Alemania",
    currentTeam: "FC Barcelona",
    league: "La Liga",
    position: "Portero",
  },
  {
    name: "Antoine Griezmann",
    country: "Francia",
    currentTeam: "Atlético Madrid",
    league: "La Liga",
    position: "Delantero",
  },
  {
    name: "Julián Álvarez",
    country: "Argentina",
    currentTeam: "Atlético Madrid",
    league: "La Liga",
    position: "Delantero",
  },
  { name: "Koke", country: "España", currentTeam: "Atlético Madrid", league: "La Liga", position: "Centrocampista" },
  { name: "Jan Oblak", country: "Eslovenia", currentTeam: "Atlético Madrid", league: "La Liga", position: "Portero" },
  { name: "Youssef En-Nesyri", country: "Marruecos", currentTeam: "Sevilla", league: "La Liga", position: "Delantero" },
  { name: "Jesús Navas", country: "España", currentTeam: "Sevilla", league: "La Liga", position: "Defensor" },
  { name: "Bono", country: "Marruecos", currentTeam: "Sevilla", league: "La Liga", position: "Portero" },
  { name: "Isco", country: "España", currentTeam: "Real Betis", league: "La Liga", position: "Centrocampista" },
  { name: "Borja Iglesias", country: "España", currentTeam: "Real Betis", league: "La Liga", position: "Delantero" },
  { name: "Claudio Bravo", country: "Chile", currentTeam: "Real Betis", league: "La Liga", position: "Portero" },
  { name: "Gerard Moreno", country: "España", currentTeam: "Villarreal", league: "La Liga", position: "Delantero" },
  { name: "Álex Baena", country: "España", currentTeam: "Villarreal", league: "La Liga", position: "Centrocampista" },
  { name: "Filip Jörgensen", country: "Dinamarca", currentTeam: "Villarreal", league: "La Liga", position: "Portero" },
  {
    name: "Mikel Oyarzabal",
    country: "España",
    currentTeam: "Real Sociedad",
    league: "La Liga",
    position: "Delantero",
  },
  {
    name: "Martin Zubimendi",
    country: "España",
    currentTeam: "Real Sociedad",
    league: "La Liga",
    position: "Centrocampista",
  },
  { name: "Álex Remiro", country: "España", currentTeam: "Real Sociedad", league: "La Liga", position: "Portero" },
  {
    name: "Iñaki Williams",
    country: "España",
    currentTeam: "Athletic Bilbao",
    league: "La Liga",
    position: "Delantero",
  },
  { name: "Nico Williams", country: "España", currentTeam: "Athletic Bilbao", league: "La Liga", position: "Extremo" },
  { name: "Unai Simón", country: "España", currentTeam: "Athletic Bilbao", league: "La Liga", position: "Portero" },
  { name: "Hugo Duro", country: "España", currentTeam: "Valencia", league: "La Liga", position: "Delantero" },

  // Premier League - Top 30
  {
    name: "Erling Haaland",
    country: "Noruega",
    currentTeam: "Manchester City",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "Kevin De Bruyne",
    country: "Bélgica",
    currentTeam: "Manchester City",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Rodri",
    country: "España",
    currentTeam: "Manchester City",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Phil Foden",
    country: "Inglaterra",
    currentTeam: "Manchester City",
    league: "Premier League",
    position: "Centrocampista",
  },
  { name: "Ederson", country: "Brasil", currentTeam: "Manchester City", league: "Premier League", position: "Portero" },
  { name: "Mohamed Salah", country: "Egipto", currentTeam: "Liverpool", league: "Premier League", position: "Extremo" },
  {
    name: "Virgil van Dijk",
    country: "Países Bajos",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Defensor",
  },
  {
    name: "Alexis Mac Allister",
    country: "Argentina",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Darwin Núñez",
    country: "Uruguay",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Delantero",
  },
  { name: "Alisson", country: "Brasil", currentTeam: "Liverpool", league: "Premier League", position: "Portero" },
  {
    name: "Bruno Fernandes",
    country: "Portugal",
    currentTeam: "Manchester United",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Marcus Rashford",
    country: "Inglaterra",
    currentTeam: "Manchester United",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "Casemiro",
    country: "Brasil",
    currentTeam: "Manchester United",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "André Onana",
    country: "Camerún",
    currentTeam: "Manchester United",
    league: "Premier League",
    position: "Portero",
  },
  {
    name: "Cole Palmer",
    country: "Inglaterra",
    currentTeam: "Chelsea",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Enzo Fernández",
    country: "Argentina",
    currentTeam: "Chelsea",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Nicolas Jackson",
    country: "Senegal",
    currentTeam: "Chelsea",
    league: "Premier League",
    position: "Delantero",
  },
  { name: "Robert Sánchez", country: "España", currentTeam: "Chelsea", league: "Premier League", position: "Portero" },
  { name: "Bukayo Saka", country: "Inglaterra", currentTeam: "Arsenal", league: "Premier League", position: "Extremo" },
  {
    name: "Martin Ødegaard",
    country: "Noruega",
    currentTeam: "Arsenal",
    league: "Premier League",
    position: "Centrocampista",
  },
  { name: "Gabriel Jesus", country: "Brasil", currentTeam: "Arsenal", league: "Premier League", position: "Delantero" },
  { name: "David Raya", country: "España", currentTeam: "Arsenal", league: "Premier League", position: "Portero" },
  {
    name: "Son Heung-min",
    country: "Corea del Sur",
    currentTeam: "Tottenham",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "James Maddison",
    country: "Inglaterra",
    currentTeam: "Tottenham",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Guglielmo Vicario",
    country: "Italia",
    currentTeam: "Tottenham",
    league: "Premier League",
    position: "Portero",
  },
  {
    name: "Alexander Isak",
    country: "Suecia",
    currentTeam: "Newcastle United",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "Bruno Guimarães",
    country: "Brasil",
    currentTeam: "Newcastle United",
    league: "Premier League",
    position: "Centrocampista",
  },
  {
    name: "Nick Pope",
    country: "Inglaterra",
    currentTeam: "Newcastle United",
    league: "Premier League",
    position: "Portero",
  },
  {
    name: "Ollie Watkins",
    country: "Inglaterra",
    currentTeam: "Aston Villa",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "Emiliano Martínez",
    country: "Argentina",
    currentTeam: "Aston Villa",
    league: "Premier League",
    position: "Portero",
  },

  // Serie A Italia - Top 30
  {
    name: "Lautaro Martínez",
    country: "Argentina",
    currentTeam: "Inter Milan",
    league: "Serie A",
    position: "Delantero",
  },
  { name: "Marcus Thuram", country: "Francia", currentTeam: "Inter Milan", league: "Serie A", position: "Delantero" },
  {
    name: "Nicolò Barella",
    country: "Italia",
    currentTeam: "Inter Milan",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Yann Sommer", country: "Suiza", currentTeam: "Inter Milan", league: "Serie A", position: "Portero" },
  { name: "Dusan Vlahovic", country: "Serbia", currentTeam: "Juventus", league: "Serie A", position: "Delantero" },
  {
    name: "Federico Chiesa",
    country: "Italia",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Extremo",
  },
  {
    name: "Manuel Locatelli",
    country: "Italia",
    currentTeam: "Juventus",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Wojciech Szczesny", country: "Polonia", currentTeam: "Juventus", league: "Serie A", position: "Portero" },
  { name: "Rafael Leão", country: "Portugal", currentTeam: "AC Milan", league: "Serie A", position: "Extremo" },
  { name: "Olivier Giroud", country: "Francia", currentTeam: "Los Angeles FC", league: "MLS", position: "Delantero" },
  { name: "Theo Hernández", country: "Francia", currentTeam: "AC Milan", league: "Serie A", position: "Defensor" },
  { name: "Mike Maignan", country: "Francia", currentTeam: "AC Milan", league: "Serie A", position: "Portero" },
  {
    name: "Victor Osimhen",
    country: "Nigeria",
    currentTeam: "Galatasaray",
    league: "Süper Lig",
    position: "Delantero",
  },
  { name: "Khvicha Kvaratskhelia", country: "Georgia", currentTeam: "Napoli", league: "Serie A", position: "Extremo" },
  {
    name: "Stanislav Lobotka",
    country: "Eslovaquia",
    currentTeam: "Napoli",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Alex Meret", country: "Italia", currentTeam: "Napoli", league: "Serie A", position: "Portero" },
  { name: "Paulo Dybala", country: "Argentina", currentTeam: "AS Roma", league: "Serie A", position: "Delantero" },
  {
    name: "Lorenzo Pellegrini",
    country: "Italia",
    currentTeam: "AS Roma",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Mile Svilar", country: "Serbia", currentTeam: "AS Roma", league: "Serie A", position: "Portero" },
  { name: "Ciro Immobile", country: "Italia", currentTeam: "Besiktas", league: "Süper Lig", position: "Delantero" },
  {
    name: "Sergej Milinkovic-Savic",
    country: "Serbia",
    currentTeam: "Al-Hilal",
    league: "Saudi Pro League",
    position: "Centrocampista",
  },
  { name: "Ivan Provedel", country: "Italia", currentTeam: "Lazio", league: "Serie A", position: "Portero" },
  { name: "Ademola Lookman", country: "Nigeria", currentTeam: "Atalanta", league: "Serie A", position: "Delantero" },
  {
    name: "Teun Koopmeiners",
    country: "Países Bajos",
    currentTeam: "Juventus",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Juan Musso", country: "Argentina", currentTeam: "Atalanta", league: "Serie A", position: "Portero" },
  { name: "Moise Kean", country: "Italia", currentTeam: "Fiorentina", league: "Serie A", position: "Delantero" },
  { name: "Riccardo Sottil", country: "Italia", currentTeam: "Fiorentina", league: "Serie A", position: "Extremo" },
  { name: "Pietro Terracciano", country: "Italia", currentTeam: "Fiorentina", league: "Serie A", position: "Portero" },
  { name: "Andrea Belotti", country: "Italia", currentTeam: "Como", league: "Serie A", position: "Delantero" },
  { name: "Samuele Ricci", country: "Italia", currentTeam: "Torino", league: "Serie A", position: "Centrocampista" },

  // Ligue 1 Francia - Top 30
  { name: "Ousmane Dembélé", country: "Francia", currentTeam: "PSG", league: "Ligue 1", position: "Extremo" },
  { name: "Randal Kolo Muani", country: "Francia", currentTeam: "PSG", league: "Ligue 1", position: "Delantero" },
  { name: "Warren Zaïre-Emery", country: "Francia", currentTeam: "PSG", league: "Ligue 1", position: "Centrocampista" },
  { name: "Gianluigi Donnarumma", country: "Italia", currentTeam: "PSG", league: "Ligue 1", position: "Portero" },
  { name: "Alexandre Lacazette", country: "Francia", currentTeam: "Lyon", league: "Ligue 1", position: "Delantero" },
  { name: "Rayan Cherki", country: "Francia", currentTeam: "Lyon", league: "Ligue 1", position: "Centrocampista" },
  { name: "Anthony Lopes", country: "Portugal", currentTeam: "Lyon", league: "Ligue 1", position: "Portero" },
  {
    name: "Pierre-Emerick Aubameyang",
    country: "Gabón",
    currentTeam: "Marseille",
    league: "Ligue 1",
    position: "Delantero",
  },
  {
    name: "Amine Harit",
    country: "Marruecos",
    currentTeam: "Marseille",
    league: "Ligue 1",
    position: "Centrocampista",
  },
  { name: "Pau López", country: "España", currentTeam: "Marseille", league: "Ligue 1", position: "Portero" },
  {
    name: "Folarin Balogun",
    country: "Estados Unidos",
    currentTeam: "AS Monaco",
    league: "Ligue 1",
    position: "Delantero",
  },
  {
    name: "Takumi Minamino",
    country: "Japón",
    currentTeam: "AS Monaco",
    league: "Ligue 1",
    position: "Centrocampista",
  },
  { name: "Radoslaw Majecki", country: "Polonia", currentTeam: "AS Monaco", league: "Ligue 1", position: "Portero" },
  { name: "Jonathan David", country: "Canadá", currentTeam: "Lille", league: "Ligue 1", position: "Delantero" },
  { name: "Edon Zhegrova", country: "Kosovo", currentTeam: "Lille", league: "Ligue 1", position: "Extremo" },
  { name: "Lucas Chevalier", country: "Francia", currentTeam: "Lille", league: "Ligue 1", position: "Portero" },
  { name: "Martin Terrier", country: "Francia", currentTeam: "Rennes", league: "Ligue 1", position: "Delantero" },
  {
    name: "Benjamin Bourigeaud",
    country: "Francia",
    currentTeam: "Rennes",
    league: "Ligue 1",
    position: "Centrocampista",
  },
  { name: "Steve Mandanda", country: "Francia", currentTeam: "Rennes", league: "Ligue 1", position: "Portero" },
  { name: "Terem Moffi", country: "Nigeria", currentTeam: "Nice", league: "Ligue 1", position: "Delantero" },
  {
    name: "Khéphren Thuram",
    country: "Francia",
    currentTeam: "Juventus",
    league: "Serie A",
    position: "Centrocampista",
  },
  { name: "Marcin Bulka", country: "Polonia", currentTeam: "Nice", league: "Ligue 1", position: "Portero" },
  { name: "Ludovic Ajorque", country: "Francia", currentTeam: "Strasbourg", league: "Ligue 1", position: "Delantero" },
  {
    name: "Habib Diarra",
    country: "Senegal",
    currentTeam: "Strasbourg",
    league: "Ligue 1",
    position: "Centrocampista",
  },
  {
    name: "Matz Sels",
    country: "Bélgica",
    currentTeam: "Nottingham Forest",
    league: "Premier League",
    position: "Portero",
  },
  { name: "Elye Wahi", country: "Francia", currentTeam: "Marseille", league: "Ligue 1", position: "Delantero" },
  {
    name: "Maghnes Akliouche",
    country: "Francia",
    currentTeam: "AS Monaco",
    league: "Ligue 1",
    position: "Centrocampista",
  },
  { name: "Yann Gboho", country: "Francia", currentTeam: "Rennes", league: "Ligue 1", position: "Extremo" },
  { name: "Gift Orban", country: "Nigeria", currentTeam: "Lyon", league: "Ligue 1", position: "Delantero" },
  { name: "Ismaël Koné", country: "Canadá", currentTeam: "Marseille", league: "Ligue 1", position: "Centrocampista" },

  // Bundesliga Alemania - Top 30
  {
    name: "Harry Kane",
    country: "Inglaterra",
    currentTeam: "Bayern Munich",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Jamal Musiala",
    country: "Alemania",
    currentTeam: "Bayern Munich",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  { name: "Leroy Sané", country: "Alemania", currentTeam: "Bayern Munich", league: "Bundesliga", position: "Extremo" },
  {
    name: "Manuel Neuer",
    country: "Alemania",
    currentTeam: "Bayern Munich",
    league: "Bundesliga",
    position: "Portero",
  },
  {
    name: "Florian Wirtz",
    country: "Alemania",
    currentTeam: "Bayer Leverkusen",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  {
    name: "Victor Boniface",
    country: "Nigeria",
    currentTeam: "Bayer Leverkusen",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Granit Xhaka",
    country: "Suiza",
    currentTeam: "Bayer Leverkusen",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  {
    name: "Lukas Hradecky",
    country: "Finlandia",
    currentTeam: "Bayer Leverkusen",
    league: "Bundesliga",
    position: "Portero",
  },
  {
    name: "Serhou Guirassy",
    country: "Guinea",
    currentTeam: "Borussia Dortmund",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Julian Brandt",
    country: "Alemania",
    currentTeam: "Borussia Dortmund",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  {
    name: "Karim Adeyemi",
    country: "Alemania",
    currentTeam: "Borussia Dortmund",
    league: "Bundesliga",
    position: "Extremo",
  },
  {
    name: "Gregor Kobel",
    country: "Suiza",
    currentTeam: "Borussia Dortmund",
    league: "Bundesliga",
    position: "Portero",
  },
  {
    name: "Christopher Nkunku",
    country: "Francia",
    currentTeam: "Chelsea",
    league: "Premier League",
    position: "Delantero",
  },
  {
    name: "Xavi Simons",
    country: "Países Bajos",
    currentTeam: "RB Leipzig",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  { name: "Loïs Openda", country: "Bélgica", currentTeam: "RB Leipzig", league: "Bundesliga", position: "Delantero" },
  { name: "Péter Gulácsi", country: "Hungría", currentTeam: "RB Leipzig", league: "Bundesliga", position: "Portero" },
  {
    name: "Omar Marmoush",
    country: "Egipto",
    currentTeam: "Eintracht Frankfurt",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Mario Götze",
    country: "Alemania",
    currentTeam: "Eintracht Frankfurt",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  {
    name: "Kevin Trapp",
    country: "Alemania",
    currentTeam: "Eintracht Frankfurt",
    league: "Bundesliga",
    position: "Portero",
  },
  {
    name: "Wout Weghorst",
    country: "Países Bajos",
    currentTeam: "TSG Hoffenheim",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Andrej Kramarić",
    country: "Croacia",
    currentTeam: "TSG Hoffenheim",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Oliver Baumann",
    country: "Alemania",
    currentTeam: "TSG Hoffenheim",
    league: "Bundesliga",
    position: "Portero",
  },
  { name: "Vincenzo Grifo", country: "Italia", currentTeam: "SC Freiburg", league: "Bundesliga", position: "Extremo" },
  {
    name: "Michael Gregoritsch",
    country: "Austria",
    currentTeam: "SC Freiburg",
    league: "Bundesliga",
    position: "Delantero",
  },
  { name: "Noah Atubolu", country: "Alemania", currentTeam: "SC Freiburg", league: "Bundesliga", position: "Portero" },
  {
    name: "Deniz Undav",
    country: "Alemania",
    currentTeam: "VfB Stuttgart",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Enzo Millot",
    country: "Francia",
    currentTeam: "VfB Stuttgart",
    league: "Bundesliga",
    position: "Centrocampista",
  },
  {
    name: "Alexander Nübel",
    country: "Alemania",
    currentTeam: "VfB Stuttgart",
    league: "Bundesliga",
    position: "Portero",
  },
  {
    name: "Maximilian Beier",
    country: "Alemania",
    currentTeam: "Borussia Dortmund",
    league: "Bundesliga",
    position: "Delantero",
  },
  {
    name: "Tim Kleindienst",
    country: "Alemania",
    currentTeam: "Borussia Mönchengladbach",
    league: "Bundesliga",
    position: "Delantero",
  },

  // Liga Portugal - Top 30
  {
    name: "Ángel Di María",
    country: "Argentina",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Extremo",
  },
  {
    name: "Viktor Gyökeres",
    country: "Suecia",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Delantero",
  },
  {
    name: "Otávio",
    country: "Brasil",
    currentTeam: "Al-Nassr",
    league: "Saudi Pro League",
    position: "Centrocampista",
  },
  { name: "Diogo Costa", country: "Portugal", currentTeam: "FC Porto", league: "Liga Portugal", position: "Portero" },
  { name: "Galeno", country: "Brasil", currentTeam: "FC Porto", league: "Liga Portugal", position: "Extremo" },
  { name: "Pepê", country: "Brasil", currentTeam: "FC Porto", league: "Liga Portugal", position: "Extremo" },
  { name: "Mehdi Taremi", country: "Irán", currentTeam: "Inter Milan", league: "Serie A", position: "Delantero" },
  { name: "Anatoliy Trubin", country: "Ucrania", currentTeam: "Benfica", league: "Liga Portugal", position: "Portero" },
  { name: "Rafa Silva", country: "Portugal", currentTeam: "Benfica", league: "Liga Portugal", position: "Extremo" },
  { name: "João Neves", country: "Portugal", currentTeam: "PSG", league: "Ligue 1", position: "Centrocampista" },
  {
    name: "Orkun Kökçü",
    country: "Turquía",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  {
    name: "Franco Israel",
    country: "Uruguay",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Portero",
  },
  {
    name: "Pedro Gonçalves",
    country: "Portugal",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  {
    name: "Morten Hjulmand",
    country: "Dinamarca",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  { name: "Trincão", country: "Portugal", currentTeam: "Sporting CP", league: "Liga Portugal", position: "Extremo" },
  {
    name: "Wenderson Galeno",
    country: "Brasil",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Extremo",
  },
  {
    name: "Stephen Eustáquio",
    country: "Canadá",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  {
    name: "Nico González",
    country: "España",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  {
    name: "Samu Omorodion",
    country: "España",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Delantero",
  },
  { name: "Arthur Cabral", country: "Brasil", currentTeam: "Benfica", league: "Liga Portugal", position: "Delantero" },
  {
    name: "Kerem Aktürkoğlu",
    country: "Turquía",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Extremo",
  },
  { name: "Álvaro Carreras", country: "España", currentTeam: "Benfica", league: "Liga Portugal", position: "Defensor" },
  {
    name: "Geovany Quenda",
    country: "Portugal",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Extremo",
  },
  {
    name: "Daniel Bragança",
    country: "Portugal",
    currentTeam: "Sporting CP",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  { name: "Paulinho", country: "Portugal", currentTeam: "Sporting CP", league: "Liga Portugal", position: "Delantero" },
  {
    name: "Fábio Vieira",
    country: "Portugal",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Centrocampista",
  },
  {
    name: "Danny Namaso",
    country: "Inglaterra",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Extremo",
  },
  {
    name: "Martim Fernandes",
    country: "Portugal",
    currentTeam: "FC Porto",
    league: "Liga Portugal",
    position: "Defensor",
  },
  {
    name: "Vangelis Pavlidis",
    country: "Grecia",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Delantero",
  },
  {
    name: "Renato Sanches",
    country: "Portugal",
    currentTeam: "Benfica",
    league: "Liga Portugal",
    position: "Centrocampista",
  },

  // Eredivisie Países Bajos - Top 30
  { name: "Steven Bergwijn", country: "Países Bajos", currentTeam: "Ajax", league: "Eredivisie", position: "Extremo" },
  { name: "Brian Brobbey", country: "Países Bajos", currentTeam: "Ajax", league: "Eredivisie", position: "Delantero" },
  { name: "Remko Pasveer", country: "Países Bajos", currentTeam: "Ajax", league: "Eredivisie", position: "Portero" },
  {
    name: "Luuk de Jong",
    country: "Países Bajos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Delantero",
  },
  {
    name: "Cody Gakpo",
    country: "Países Bajos",
    currentTeam: "Liverpool",
    league: "Premier League",
    position: "Extremo",
  },
  {
    name: "Jerdy Schouten",
    country: "Países Bajos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Walter Benítez",
    country: "Argentina",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Portero",
  },
  {
    name: "Santiago Giménez",
    country: "México",
    currentTeam: "Feyenoord",
    league: "Eredivisie",
    position: "Delantero",
  },
  { name: "Igor Paixão", country: "Brasil", currentTeam: "Feyenoord", league: "Eredivisie", position: "Extremo" },
  {
    name: "Quinten Timber",
    country: "Países Bajos",
    currentTeam: "Feyenoord",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Timon Wellenreuther",
    country: "Alemania",
    currentTeam: "Feyenoord",
    league: "Eredivisie",
    position: "Portero",
  },
  {
    name: "Memphis Depay",
    country: "Países Bajos",
    currentTeam: "Corinthians",
    league: "Brasileirão",
    position: "Delantero",
  },
  {
    name: "Georginio Wijnaldum",
    country: "Países Bajos",
    currentTeam: "Al-Ettifaq",
    league: "Saudi Pro League",
    position: "Centrocampista",
  },
  {
    name: "Davy Klaassen",
    country: "Países Bajos",
    currentTeam: "Ajax",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Kenneth Taylor",
    country: "Países Bajos",
    currentTeam: "Ajax",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  { name: "Jorrel Hato", country: "Países Bajos", currentTeam: "Ajax", league: "Eredivisie", position: "Defensor" },
  {
    name: "Malik Tillman",
    country: "Estados Unidos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Johan Bakayoko",
    country: "Bélgica",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Extremo",
  },
  {
    name: "Ricardo Pepi",
    country: "Estados Unidos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Delantero",
  },
  {
    name: "Calvin Stengs",
    country: "Países Bajos",
    currentTeam: "Feyenoord",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  { name: "Dávid Hancko", country: "Eslovaquia", currentTeam: "Feyenoord", league: "Eredivisie", position: "Defensor" },
  { name: "Anis Hadj Moussa", country: "Argelia", currentTeam: "Feyenoord", league: "Eredivisie", position: "Extremo" },
  { name: "Chuba Akpom", country: "Inglaterra", currentTeam: "Ajax", league: "Eredivisie", position: "Delantero" },
  {
    name: "Kristian Hlynsson",
    country: "Islandia",
    currentTeam: "Ajax",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  { name: "Mika Godts", country: "Bélgica", currentTeam: "Ajax", league: "Eredivisie", position: "Extremo" },
  {
    name: "Guus Til",
    country: "Países Bajos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Ismael Saibari",
    country: "Marruecos",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  {
    name: "Hirving Lozano",
    country: "México",
    currentTeam: "PSV Eindhoven",
    league: "Eredivisie",
    position: "Extremo",
  },
  { name: "Ayase Ueda", country: "Japón", currentTeam: "Feyenoord", league: "Eredivisie", position: "Delantero" },
  {
    name: "Ramiz Zerrouki",
    country: "Argelia",
    currentTeam: "Feyenoord",
    league: "Eredivisie",
    position: "Centrocampista",
  },

  // Selecciones Nacionales y Estrellas Internacionales
  { name: "Lionel Messi", country: "Argentina", currentTeam: "Inter Miami", league: "MLS", position: "Delantero" },
  {
    name: "Cristiano Ronaldo",
    country: "Portugal",
    currentTeam: "Al-Nassr",
    league: "Saudi Pro League",
    position: "Delantero",
  },
  { name: "Neymar Jr", country: "Brasil", currentTeam: "Al-Hilal", league: "Saudi Pro League", position: "Extremo" },
  {
    name: "Karim Benzema",
    country: "Francia",
    currentTeam: "Al-Ittihad",
    league: "Saudi Pro League",
    position: "Delantero",
  },
  { name: "Sadio Mané", country: "Senegal", currentTeam: "Al-Nassr", league: "Saudi Pro League", position: "Extremo" },
  { name: "Riyad Mahrez", country: "Argelia", currentTeam: "Al-Ahli", league: "Saudi Pro League", position: "Extremo" },
  {
    name: "N'Golo Kanté",
    country: "Francia",
    currentTeam: "Al-Ittihad",
    league: "Saudi Pro League",
    position: "Centrocampista",
  },
  {
    name: "Fabinho",
    country: "Brasil",
    currentTeam: "Al-Ittihad",
    league: "Saudi Pro League",
    position: "Centrocampista",
  },
  {
    name: "Jordan Henderson",
    country: "Inglaterra",
    currentTeam: "Ajax",
    league: "Eredivisie",
    position: "Centrocampista",
  },
  { name: "Sergio Ramos", country: "España", currentTeam: "PSG", league: "Ligue 1", position: "Defensor" },
  {
    name: "Luka Modrić",
    country: "Croacia",
    currentTeam: "Real Madrid",
    league: "La Liga",
    position: "Centrocampista",
  },
  { name: "Toni Kroos", country: "Alemania", currentTeam: "Retirado", league: "Retirado", position: "Centrocampista" },
  { name: "Gareth Bale", country: "Gales", currentTeam: "Retirado", league: "Retirado", position: "Extremo" },
  { name: "Luis Suárez", country: "Uruguay", currentTeam: "Inter Miami", league: "MLS", position: "Delantero" },
  { name: "Sergio Busquets", country: "España", currentTeam: "Inter Miami", league: "MLS", position: "Centrocampista" },
]

export function searchPlayers(query: string): Player[] {
  if (!query.trim()) return []

  const normalizedQuery = normalizeText(query)

  return ALL_PLAYERS.filter((player) => {
    const normalizedPlayerName = normalizeText(player.name)
    const normalizedCountry = normalizeText(player.country)
    const normalizedTeam = normalizeText(player.currentTeam)
    const normalizedLeague = normalizeText(player.league)
    const normalizedPosition = normalizeText(player.position)

    return (
      normalizedPlayerName.includes(normalizedQuery) ||
      normalizedCountry.includes(normalizedQuery) ||
      normalizedTeam.includes(normalizedQuery) ||
      normalizedLeague.includes(normalizedQuery) ||
      normalizedPosition.includes(normalizedQuery)
    )
  }).slice(0, 10) // Limitar a 10 resultados para mejor UX
}

// Jugadores por categoría para facilitar la navegación
export const PLAYERS_BY_CATEGORY = {
  featured: FEATURED_PLAYERS,
  argentina: ALL_PLAYERS.filter((player) => player.league === "Liga Profesional").slice(0, 30),
  brasil: ALL_PLAYERS.filter((player) => player.league === "Brasileirão").slice(0, 30),
  europe: ALL_PLAYERS.filter((player) =>
    ["La Liga", "Premier League", "Serie A", "Ligue 1", "Bundesliga"].includes(player.league),
  ).slice(0, 30),
  legends: ALL_PLAYERS.filter((player) =>
    ["Inter Miami", "Al-Nassr", "Al-Hilal", "Al-Ittihad"].includes(player.currentTeam),
  ).slice(0, 20),
}
